#!/usr/bin/env python
# coding: utf-8
import sys
import csv

from dbfread import DBF


def write_csv(table):
    writer = csv.writer(sys.stdout)
    writer.writerow(table.field_names)
    for record in table:
        writer.writerow(list(record.values()))

if __name__ == "__main__":
    file_name = sys.argv[1]
    table = DBF(file_name)
    write_csv(table)
